# Generated by Django 4.1.7 on 2023-06-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tip",
            name="amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
