# Generated by Django 4.1.7 on 2023-03-17 22:37

from django.db import migrations, models
import enumfields.fields
import food_and_beverage.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('units_available', models.PositiveIntegerField(null=True)),
                ('type', enumfields.fields.EnumIntegerField(enum=food_and_beverage.enums.BeverageType)),
                ('alcoholic', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('units_available', models.PositiveIntegerField(null=True)),
                ('type', enumfields.fields.EnumIntegerField(enum=food_and_beverage.enums.DishType)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
