# Generated by Django 4.1.7 on 2023-04-05 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("food_and_beverage", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Dish",
            new_name="Food",
        ),
    ]
