# Generated by Django 4.1.7 on 2023-03-17 22:37

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import orders.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', enumfields.fields.EnumIntegerField(default=2, enum=orders.enums.OrderPaymentStatus)),
                ('preparation_status', enumfields.fields.EnumIntegerField(default=1, enum=orders.enums.OrderPreparationSatus)),
                ('ordering_type', enumfields.fields.EnumIntegerField(default=2, enum=orders.enums.OrderingType)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.table')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.waiter')),
            ],
        ),
    ]
