# Generated by Django 4.1.7 on 2023-06-03 05:39

from django.db import migrations, models
import enumfields.fields
import orders.enums


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_table_alter_order_waiter"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="table",
            name="status",
            field=enumfields.fields.EnumIntegerField(
                default=1, enum=orders.enums.TableStatus
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="number",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
