# Generated by Django 4.1.7 on 2023-06-09 21:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_last_update_timestamp_order_submit_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_food_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, editable=False, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_beverage_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, editable=False, max_digits=10, null=True
            ),
        ),
    ]
